name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            extra-args: ''
          - target: aarch64-unknown-linux-gnu
            extra-args: '--use-napi-cross'
          - target: x86_64-unknown-linux-musl
            extra-args: '-x'
          - target: x86_64-apple-darwin
            extra-args: '-x'
          - target: aarch64-apple-darwin
            extra-args: '-x'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install zig
        uses: mlugg/setup-zig@v2

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cross-compilation tools
        run: cargo binstall -y cargo-zigbuild cargo-xwin

      - name: Build native binding (${{ matrix.target }})
        run: |
          bunx napi build --release --platform --esm --strip \
            --output-dir dist/napi/ \
            --target "${{ matrix.target }}" ${{ matrix.extra-args }}
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.13'
          TARGET_CFLAGS: '-std=gnu11'

      - name: Upload native binding
        uses: actions/upload-artifact@v4
        with:
          name: native-binding-${{ matrix.target }}
          path: dist/napi/*.node
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Download native bindings
        uses: actions/download-artifact@v4
        with:
          pattern: native-binding-*
          path: dist/napi
          merge-multiple: true

      - name: Build JavaScript
        run: bun run build:js

      - name: Check formatting
        run: nix fmt -- --fail-on-change

      - name: Run Nix flake checks
        run: nix flake check

      - name: Run clippy
        run: cargo clippy

      - name: Run eslint
        run: bun run lint

      - name: Run Rust tests
        run: cargo test

      - name: Run JavaScript tests
        run: bun test

      - name: Semantic Release
        run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
